-- Original Path: .\WoWUI\Interface\AddOns\Blizzard_Colors\Shared\ColorConstants.lua
-- Auto-generated LuaLS Annotations, do not edit manually
---@meta _
---@class MATERIAL_TEXT_COLOR_TABLE
MATERIAL_TEXT_COLOR_TABLE = 
{
	["Default"] = DEFAULT_MATERIAL_TEXT_COLOR,
	["Stone"] = STONE_MATERIAL_TEXT_COLOR,
	["Parchment"] = PARCHMENT_MATERIAL_TEXT_COLOR,
	["Marble"] = MARBLE_MATERIAL_TEXT_COLOR,
	["Silver"] = SILVER_MATERIAL_TEXT_COLOR,
	["Bronze"] = BRONZE_MATERIAL_TEXT_COLOR,
	["ParchmentLarge"] = PARCHMENTLARGE_MATERIAL_TEXT_COLOR,
};

---@class MATERIAL_TITLETEXT_COLOR_TABLE
MATERIAL_TITLETEXT_COLOR_TABLE = 
{
	["Default"] = DEFAULT_MATERIAL_TITLETEXT_COLOR,
	["Stone"] = STONE_MATERIAL_TITLETEXT_COLOR,
	["Parchment"] = PARCHMENT_MATERIAL_TITLETEXT_COLOR,
	["Marble"] = MARBLE_MATERIAL_TITLETEXT_COLOR,
	["Silver"] = SILVER_MATERIAL_TITLETEXT_COLOR,
	["Bronze"] = BRONZE_MATERIAL_TITLETEXT_COLOR,
	["ParchmentLarge"] = PARCHMENTLARGE_MATERIAL_TITLETEXT_COLOR,
};