-- Original Path: .\WoWUI\Interface\AddOns\Blizzard_BlackMarketUI\Localization.lua
-- Auto-generated LuaLS Annotations, do not edit manually
---@meta _
-- This file is executed at the end of addon load
