-- Original Path: .\WoWUI\Interface\AddOns\Blizzard_DeclensionFrameGlue\Classic\DeclensionFrame.lua
-- Auto-generated LuaLS Annotations, do not edit manually
---@meta _
-- Overriden by the locale-specific versions