---@meta
--* GENERATED BY gemini-2.0-flash

---Tracks an achievement.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_AddTrackedAchievement)
---@param achievementID number ID of the achievement to add to tracking.
function AddTrackedAchievement(achievementID) end

---Returns the number of tracked achievements.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNumTrackedAchievements)
---@return number numTracked - number of achievements you are currently tracking, up to 10.
function GetNumTrackedAchievements() end

---Returns the currently tracked achievements.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTrackedAchievements)
---@return number ... id1, id2, id3, ... The IDs of the achievements being tracked.
function GetTrackedAchievements() end

---Returns if an achievement is currently being tracked.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsTrackedAchievement)
---@param achievementID number Uniquely identifies each achievement
---@return boolean eligible
function IsTrackedAchievement(achievementID) end

---Untracks an achievement from the WatchFrame.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_RemoveTrackedAchievement)
---@param achievementID number ID of the achievement to add to tracking.
function RemoveTrackedAchievement(achievementID) end

