---@meta
--* GENERATED BY gemini-2.0-flash

---Accepts a pending arena team invitation.<br>
---Only one arena team invitation may be pending at any time.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_AcceptArenaTeam)
function AcceptArenaTeam() end

---Disbands an Arena Team if the player is the team captain.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_ArenaTeamDisband)
---@param index number Index of the arena team to delete, index can be a value of 1 through 3.
function ArenaTeamDisband(index) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_ArenaTeamInviteByName)
---@param index number
---@param target string
function ArenaTeamInviteByName(index, target) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_ArenaTeamLeave)
---@param index number
function ArenaTeamLeave(index) end

---Requests the arena team information from the server.<br>
---Because this sends a request to the server, you will not get the data instantly you must register and watch for the ARENA_TEAM_ROSTER_UPDATE event.
---[Documentation](https://warcraft.wiki.gg/wiki/API_ArenaTeamRoster)
---@param index number Index of the arena team to request information from, 1 through 3.
function ArenaTeamRoster(index) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_ArenaTeamSetLeaderByName)
---@param index number
---@param target string
function ArenaTeamSetLeaderByName(index, target) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_ArenaTeamUninviteByName)
---@param index number
---@param target string
function ArenaTeamUninviteByName(index, target) end

---Declines a pending arena team invitation.<br>
---Only one arena team invitation may be pending at any time.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_DeclineArenaTeam)
function DeclineArenaTeam() end

---Requests information regarding the arena team that the player is in.<br>
---Team information is not kept up to date ARENA_TEAM_UPDATE is fired when the client gets the team information.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetArenaTeam)
---@param index number Index of the team you want information on, can be a value between 1 and 3.
---@return string? teamName Teams name, nil if they aren't on a team or the data wasn't received yet.
---@return number? teamSize Team size (2, 3 or 5)
---@return number? teamRating Teams rating, for a team that hasn't played any games this season it'll be 1500
---@return number? weekPlayed Total games the team has played for the current week
---@return number? weekWins Total games the team has won for the current week
---@return number? seasonPlayed Total games that the team has played this season
---@return number? seasonWins Total games that the team has played this season
---@return number? playerPlayed Total games that the player has played this week
---@return number? seasonPlayerPlayed Total games that the player has played this season
---@return number? teamRank Teams current ranking, this is updated once a week typically when points are calculated
---@return number? personalRating Players personal rating with this team
---@return number? backgroundRed Amount of red in the teams banner background
---@return number? backgroundGreen Amount of green in the teams banner background
---@return number? backgroundBlue Amount of blue in the teams banner background
---@return number? emblem Emblem graphic name
---@return number? emblemRed Amount of red in the teams emblem color
---@return number? emblemGreen Amount of green in the teams emblem color
---@return number? emblemBlue Amount of blue in the teams emblem color
---@return number? border Border graphic name
---@return number? borderRed Amount of red in the teams border color
---@return number? borderGreen Amount of green in the teams border color
---@return number? borderBlue Amount of blue in the teams border color
function GetArenaTeam(index) end

---Returns the index of an arena team for the specified team size.<br>
---This API only exists in Cata Classic and Classic Era.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetArenaTeamIndexBySize)
---@param size number team size (number of people), i.e. 2, 3, or 5.
---@return number? index arena team index for the specified team size, or nil if the player is not in a team of the specified size.
function GetArenaTeamIndexBySize(size) end

---Requests information regarding the arena team that the player is in, see Returns for a full list of what this returns.<br>
---Removed in Patch 5.4.0.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetArenaTeamRosterInfo)
---@param teamindex number Index of the team you want information on, can be a value between 1 and 3.
---@param playerindex number Index of the team member. Starts at 1.
---@return string name Name of the player.
---@return number rank 0 denotes team captain, while 1 denotes a regular member.
---@return number level Player level.
---@return string class The localized class of the player.
---@return number? online 1 denotes the player being online. nil denotes the player as offline.
---@return number played Number of games this player has played this week.
---@return number win Number of games this player has won this week.
---@return number seasonPlayed Number of games played the entire season.
---@return number seasonWin Number of games this player has won this week.
---@return number personalRating Players personal rating with this team
function GetArenaTeamRosterInfo(teamindex, playerindex) end

