---@meta
--* GENERATED BY gemini-2.0-flash

---Determine if a new auction house query can be sent (via QueryAuctionItems()).<br>
---There is always a short delay (usually less than a second) after each query before another query can take place. Full ("getall") queries are only allowed once every ~15 minutes.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_CanSendAuctionQuery)
---@return boolean canQuery - True if a normal auction house query can be made
---@return boolean canQueryAll - True if a full ("getall") auction house query can be made (added in 2.3)
function CanSendAuctionQuery() end

---Stops the process of listing multiple stacks of an item on the auction house.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_CancelSell)
function CancelSell() end

---Puts the currently 'picked up' item into the 'create auction' slot.<br>
---In the Auction house, under 'auctions', 'create auction', there is an 'auction item' slot.
---[Documentation](https://warcraft.wiki.gg/wiki/API_ClickAuctionSellItemButton)
---@param frame unknown
---@param button string
---@param boolean boolean
function ClickAuctionSellItemButton(frame, button, boolean) end

---Closes the AuctionFrame if opened.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_CloseAuctionHouse)
function CloseAuctionHouse() end

---Retrieves info about one Battle Pet in the current retrieved list of Battle Pets from the Auction House.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetAuctionItemBattlePetInfo)
---@param type string "list", "bidder", or "owner"
---@param index number The index of the item in the list to retrieve info from (normally 1-50, inclusive).
---@return number creatureID An indexing value Blizzard uses to number NPCs.
---@return number displayID An indexing value Blizzard uses to number model/skin combinations.
function GetAuctionItemBattlePetInfo(type, index) end

---Retrieves info about one item in the current retrieved list of items from the Auction House.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetAuctionItemInfo)
---@param type string "list", "bidder", or "owner"
---@param index number The index of the item in the list to retrieve info from (normally 1-50, inclusive)
---@return string name the name of the item
---@return number texture the fileID of the texture of the item
---@return number count the number of items in the auction item, zero if item is "sold" in the "owner" auctions
---@return Enum.ItemQuality quality
---@return boolean canUse true if the user can use the item, false if not
---@return number level the level required to use the item
---@return string levelColHeader The preceding level return value changes depending on the value of levelColHeader
---@return number minBid the starting bid price
---@return number minIncrement the minimum amount of item at which to put the next bid
---@return number buyoutPrice zero if no buy out, otherwise it contains the buyout price of the auction item
---@return number bidAmount the current highest bid, zero if no one has bid yet
---@return string? highBidder returns name of highest bidder, nil otherwise
---@return string? bidderFullName returns bidders full name if from virtual realm, nil otherwise
---@return string owner the player that is selling the item
---@return string? ownerFullName returns owners full name if from virtual realm, nil otherwise
---@return number saleStatus 1 for sold 0 for unsold
---@return number itemId item id
---@return boolean hasAllInfo was everything returned
function GetAuctionItemInfo(type, index) end

---Retrieves the itemLink of one item in the current retrieved list of items from the Auction House.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetAuctionItemLink)
---@param type string "list", "bidder", or "owner"
---@param index number The index of the item in the list to retrieve info from (normally 1-50, inclusive)
---@return string? itemLink The itemLink for the specified item or nil, if type and/or index is invalid.
function GetAuctionItemLink(type, index) end

---Gets a list of the sub-classes for an Auction House item class.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetAuctionItemSubClasses)
---@param classID number ID of the item class.
---@return number ... subClass1, subClass2, subClass3 The valid subclasses for an item class.
function GetAuctionItemSubClasses(classID) end

---Retrieves the time left for a item in the Auction House.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetAuctionItemTimeLeft)
---@param type string "list", "bidder", or "owner"
---@param index number The index of the item in the list to retrieve info from (normally 1-50, inclusive)
---@return number timeleft number between 1 and 4 (1: short, 2: medium, 3: long, 4: very long)
function GetAuctionItemTimeLeft(type, index) end

---Returns information about the item in the 'create auction' slot.<br>
---In the Auction house, under 'auctions', 'create auction', there is an 'auction item' slot.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetAuctionSellItemInfo)
---@return string? name the name of the item
---@return number? texture the fileID of the texture of the item
---@return number? count the number of items in the auction item, zero if item is "sold" in the "owner" auctions
---@return Enum.ItemQuality? quality
---@return boolean? canUse true if the user can use the item, false if not
---@return number? price the starting bid price
---@return number? pricePerUnit the minimum amount of item at which to put the next bid
---@return number? stackCount the number of items in the stack
---@return number? totalCount the total number of items
---@return number? itemID item id
function GetAuctionSellItemInfo() end

---Retrieves the number of auction items of a certain type.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNumAuctionItems)
---@param type string "list", "bidder", or "owner"
---@return number batch The size of the batch being viewed, 50 for a page view.
---@return number count The total number of items in the query.
function GetNumAuctionItems(type) end

---Updates owned auction list.<br>
---Useful for when AUCTION_OWNED_LIST_UPDATE fires but the list isn't actually updated until you switch to the tab.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetOwnerAuctionItems)
function GetOwnerAuctionItems() end

---Returns the sorting for a column on the auction house display.<br>
---This API only exists in Cata Classic and Classic Era. Removed in Patch 8.3.0.
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsAuctionSortReversed)
---@param type string "list", "bidder", or "owner"
---@param sort string "quality", "level", "status", "duration", "bid", "name", or "buyout"
---@return number? 1 if the auction list is sorted by this column, nil otherwise
function IsAuctionSortReversed(type, sort) end

---Places a bid on the selected auction item.<br>
---It is important to know that this function can only be successfully called after a hardware event, e.g. mouse click on a prompt since patch 2.0.
---[Documentation](https://warcraft.wiki.gg/wiki/API_PlaceAuctionBid)
---@param type string "list", "bidder", or "owner"
---@param index number The index of the item in the list to bid on (normally 1-50, inclusive)
---@param bid number The amount of money to bid in copper.
function PlaceAuctionBid(type, index, bid) end

---Starts the auction you have created in the Create Auction panel.<br>
---This function is restricted and requires a hardware event.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_PostAuction)
---@param minBid number The minimum bid price for this auction in copper.
---@param buyoutPrice number The buyout price for this auction in copper.
---@param runTime number The duration for which the auction should be posted.
---@param stackSize number The size of each stack to be posted.
---@param numStacks number The number of stacks to post.
function PostAuction(minBid, buyoutPrice, runTime, stackSize, numStacks) end

---Queries the server for information about current auctions, only when CanSendAuctionQuery() is true.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_QueryAuctionItems)
---@param text string A part of the item's name, or an empty string; limited to 63 bytes.
---@param minLevel number? Minimum usable level requirement for items
---@param maxLevel number? Maximum usable level requirement for items
---@param page number What page in the auctionhouse this shows up. Note that pages start at 0.
---@param usable boolean Restricts items to those usable by the current character.
---@param rarity Enum.ItemQuality? Restricts the quality of the items found.
---@param getAll boolean Download the entire auction house as one single page; see other details below.
---@param exactMatch boolean Will only items whose whole name is the same as searchString be found.
---@param filterData table?
function QueryAuctionItems(text, minLevel, maxLevel, page, usable, rarity, getAll, exactMatch, filterData) end

---Selects a specific item in the auction house.
---This API only exists in Cata Classic and Classic Era. Removed in Patch 8.3.0.
---[Documentation](https://warcraft.wiki.gg/wiki/API_SetSelectedAuctionItem)
---@param type string "list", "bidder", or "owner"
---@param index number The index of the item in the list to retrieve info from (normally 1-50, inclusive)
function SetSelectedAuctionItem(type, index) end

---Sorts the auction house display. Deprecated around Patch 2.0, see SortAuctionSetSort() which is almost functionally the same.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_SortAuctionItems)
---@param type string One of "list", "bidder", or "owner".
---@param sort string One of "quality", "level", "status", "duration", "bid", "name", or "buyout".
function SortAuctionItems(type, sort) end

---Sets the column by which the auction house sorts query results.<br>
---This applies after the next search query or call to SortAuctionApplySort(type).<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_SortAuctionSetSort)
---@param type string One of "list", "bidder", or "owner".
---@param column string One of "quality", "level", "status", "duration", "bid", "name", "buyout", or "unitprice".
---@param reverse boolean Should the sort order be reversed.
function SortAuctionSetSort(type, column, reverse) end

---Starts the auction you have created in the Create Auction panel.<br>
---This API is deprecated and no longer works, replaced by <a href="/wiki/API_PostAuction" title="API PostAuction">PostAuction</a>().<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_StartAuction)
---@param minBid number The minimum bid price for this auction in copper.
---@param buyoutPrice number The buyout price for this auction in copper.
---@param runTime number The duration for which the auction should be posted.
---@param stackSize number The size of each stack to be posted.
---@param numStacks number The number of stacks to post.
function StartAuction(minBid, buyoutPrice, runTime, stackSize, numStacks) end

