---@meta
--* GENERATED BY gemini-2.0-flash

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_BarberShop.CycleCharCustomization)
---@param type Enum.CharCustomizationType
---@param forward boolean
function C_BarberShop.CycleCharCustomization(type, forward) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_BarberShop.GetBarbersChoiceCost)
---@return number cost
function C_BarberShop.GetBarbersChoiceCost() end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_BarberShop.GetCustomizationTypeInfo)
---@param type Enum.CharCustomizationType
---@return string customizationName
---@return string name
---@return boolean isCurrent
function C_BarberShop.GetCustomizationTypeInfo(type) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_BarberShop.IsValidCustomizationType)
---@param type Enum.CharCustomizationType
---@return boolean isValid
function C_BarberShop.IsValidCustomizationType(type) end

---Returns whether the currently visible body type at the barber shop is different than what the character had before visiting.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_BarberShop.IsViewingNativeSex)
---@return boolean isNativeSex # true if the character hasn't changed body type in the barber shop UI, otherwise false
function C_BarberShop.IsViewingNativeSex() end

---Returns whether the currently visible body type at the barber shop is the same as sexId.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_BarberShop.IsViewingVisibleSex)
---@param sex number Ranging from 0 for body type 1 (masculine/male) to 1 for body type 2 (feminine/female)
---@return boolean isVisibleSex # true if the visible body type at barber shop UI matches sex, otherwise false
function C_BarberShop.IsViewingVisibleSex(sex) end

---Needs summary.
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_BarberShop.SetPortraitTexture)
---@param texture Texture
---@param raceID number
---@param sex number
function C_BarberShop.SetPortraitTexture(texture, raceID, sex) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_ConfirmBarbersChoice)
function ConfirmBarbersChoice() end

