---@meta
--* GENERATED BY gemini-2.0-flash

---Returns information about the specified toon of a RealID friend.<br>
---API Changed from BNGetToonInfo to BNGetGameAccountInfo in Patch 6.2.4.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_BNGetFriendGameAccountInfo)
---@param friendIndex number Ranging from 1 to BNGetNumFriendGameAccounts()
---@return boolean hasFocus Whether or not this toon is the one currently being displayed in Blizzard's FriendFrame.
---@return string characterName The name of the logged in toon/character.
---@return string client Either "WoW", "S2", "WTCG", "App", "Hero", "Pro", "CLNT", or "D3" for World of Warcraft, StarCraft 2, Hearthstone, BNet Application, Heroes of the Storm, Overwatch, another client, or Diablo 3.
---@return string realmName The name of the logged in realm.
---@return number realmID The ID for the logged in realm.
---@return string faction The faction name (i.e., "Alliance" or "Horde").
---@return string race The localized race name (e.g., "Blood Elf").
---@return string class The localized class name (e.g., "Death Knight").
---@return string guild Seems to return "" even if the player is in a guild.
---@return string zoneName The localized zone name (e.g., "The Undercity").
---@return string level The current level (e.g., "90").
---@return string gameText For WoW, returns "zoneName - realmName". For StarCraft 2 and Diablo 3, returns the location or activity the player is currently engaged in.
---@return string broadcastText The Battle.Net broadcast message.
---@return number broadcastTime The number of seconds elapsed since the current broadcast message was sent.
---@return boolean canSoR Whether or not this friend can receive a Scroll of Resurrection.
---@return number toonID A unique numeric identifier for the friend's character during this session.
---@return number bnetIDAccount
---@return boolean isGameAFK
---@return boolean isGameBusy
function BNGetFriendGameAccountInfo(friendIndex) end

---Returns information about the specified RealID friend.<br>
---bnetAccountID, accountName, battleTag, isBattleTagPresence, characterName, bnetIDGameAccount, client, isOnline, lastOnline, isAFK, isDND, messageText, noteText, isRIDFriend, messageTime, canSoR, isReferAFriend, canSummonFriend<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_BNGetFriendInfo)
---@param friendIndex number The index on the friends list for this RealID friend, ranging from 1 to BNGetNumFriends()
---@return number bnetAccountID A temporary ID for the friend's battle.net account during this session.
---@return string accountName An escape sequence (starting with |K) representing the friend's full name or BattleTag name.
---@return string battleTag A nickname and number that when combined, form a unique string that identifies the friend (e.g., "Nickname#0001").
---@return boolean isBattleTagPresence Whether or not the friend is known by their BattleTag.
---@return string characterName The name of the logged in character.
---@return number bnetIDGameAccount A unique numeric identifier for the friend's game account during this session.
---@return string client See BNET_CLIENT
---@return boolean isOnline Whether or not the friend is online.
---@return number lastOnline The number of seconds elapsed since this friend was last online (from the epoch date of January 1, 1970). Returns nil if currently online.
---@return boolean isAFK Whether or not the friend is flagged as Away.
---@return boolean isDND Whether or not the friend is flagged as Busy.
---@return string messageText The friend's Battle.Net broadcast message.
---@return string noteText The contents of the player's note about this friend.
---@return boolean isRIDFriend Returns true for RealID friends and false for BattleTag friends.
---@return number messageTime The number of seconds elapsed since the current broadcast message was sent.
---@return boolean canSoR Whether or not this friend can receive a Scroll of Resurrection.
---@return boolean isReferAFriend
---@return boolean canSummonFriend
function BNGetFriendInfo(friendIndex) end

---Returns information about the specified RealID friend.
---[Documentation](https://warcraft.wiki.gg/wiki/API_BNGetFriendInfo)
---@param bnetAccountID number A unique numeric identifier for this friend's battle.net account for the current session
---@return number bnetAccountID A temporary ID for the friend's battle.net account during this session.
---@return string accountName An escape sequence (starting with |K) representing the friend's full name or BattleTag name.
---@return string battleTag A nickname and number that when combined, form a unique string that identifies the friend (e.g., "Nickname#0001").
---@return boolean isBattleTagPresence Whether or not the friend is known by their BattleTag.
---@return string characterName The name of the logged in character.
---@return number bnetIDGameAccount A unique numeric identifier for the friend's game account during this session.
---@return string client See BNET_CLIENT
---@return boolean isOnline Whether or not the friend is online.
---@return number lastOnline The number of seconds elapsed since this friend was last online (from the epoch date of January 1, 1970). Returns nil if currently online.
---@return boolean isAFK Whether or not the friend is flagged as Away.
---@return boolean isDND Whether or not the friend is flagged as Busy.
---@return string messageText The friend's Battle.Net broadcast message.
---@return string noteText The contents of the player's note about this friend.
---@return boolean isRIDFriend Returns true for RealID friends and false for BattleTag friends.
---@return number messageTime The number of seconds elapsed since the current broadcast message was sent.
---@return boolean canSoR Whether or not this friend can receive a Scroll of Resurrection.
---@return boolean isReferAFriend
---@return boolean canSummonFriend
function BNGetFriendInfoByID(bnetAccountID) end

---Returns information about the specified toon of a RealID friend.<br>
---API Changed from BNGetToonInfo to BNGetGameAccountInfo in Patch 6.2.4.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_BNGetFriendGameAccountInfo)
---@param friendIndex number Ranging from 1 to BNGetNumFriendGameAccounts()
---@return boolean hasFocus Whether or not this toon is the one currently being displayed in Blizzard's FriendFrame.
---@return string characterName The name of the logged in toon/character.
---@return string client Either "WoW", "S2", "WTCG", "App", "Hero", "Pro", "CLNT", or "D3" for World of Warcraft, StarCraft 2, Hearthstone, BNet Application, Heroes of the Storm, Overwatch, another client, or Diablo 3.
---@return string realmName The name of the logged in realm.
---@return number realmID The ID for the logged in realm.
---@return string faction The faction name (i.e., "Alliance" or "Horde").
---@return string race The localized race name (e.g., "Blood Elf").
---@return string class The localized class name (e.g., "Death Knight").
---@return string guild Seems to return "" even if the player is in a guild.
---@return string zoneName The localized zone name (e.g., "The Undercity").
---@return string level The current level (e.g., "90").
---@return string gameText For WoW, returns "zoneName - realmName". For StarCraft 2 and Diablo 3, returns the location or activity the player is currently engaged in.
---@return string broadcastText The Battle.Net broadcast message.
---@return number broadcastTime The number of seconds elapsed since the current broadcast message was sent.
---@return boolean canSoR Whether or not this friend can receive a Scroll of Resurrection.
---@return number toonID A unique numeric identifier for the friend's character during this session.
---@return number bnetIDAccount
---@return boolean isGameAFK
---@return boolean isGameBusy
function BNGetFriendGameAccountInfo(friendIndex) end

---Returns information on the game the Battle.net friend is playing.<br>
---Also available as C_BattleNet.GetGameAccountInfoByID and C_BattleNet.GetGameAccountInfoByGUID.
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_BattleNet.GetFriendGameAccountInfo)
---@param friendIndex number Index ranging from 1 to BNGetNumFriends()
---@param accountIndex number Index ranging from 1 to C_BattleNet.GetFriendNumGameAccounts()
---@return BNetGameAccountInfo? gameAccountInfo
function C_BattleNet.GetFriendGameAccountInfo(friendIndex, accountIndex) end

---Returns the specified Battle.net friend's number of toons.<br>
---This function returns the number of ACCOUNTS a player has that are identified with a given battletag ID rather than the number of characters on a given account.
---[Documentation](https://warcraft.wiki.gg/wiki/API_BNGetNumFriendGameAccounts)
---@param friendIndex number The Battle.net friend's index on the friendslist
---@return number The number of accounts or 0 if friend is not online.
function BNGetNumFriendGameAccounts(friendIndex) end

---Returns whether high resolution textures are installed.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_BattleNet.AreHighResTexturesInstalled)
---@return boolean installed
function C_BattleNet.AreHighResTexturesInstalled() end

