---@meta
--* GENERATED BY gemini-2.0-flash

---Returns the player's currently channeling spell.<br>
---In Classic only channeling information for the player is available.
---[Documentation](https://warcraft.wiki.gg/wiki/API_ChannelInfo)
---@return string? name The name of the spell, or nil if no spell is being channeled.
---@return string? text The name to be displayed.
---@return number? texture FileID
---@return number? startTime Specifies when channeling began in milliseconds (corresponds to GetTime()*1000).
---@return number? endTime Specifies when channeling will end in milliseconds (corresponds to GetTime()*1000).
---@return boolean? isTradeSkill
---@return boolean? notInterruptible This is always nil.
---@return number? spellID
function ChannelInfo() end

