---@meta
--* GENERATED BY gemini-2.0-flash

---Returns if a player can be reported.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_ChatInfo.CanReportPlayer)
---@param playerLocation PlayerLocationMixin
---@return boolean canReport
function C_ChatInfo.CanReportPlayer(playerLocation) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_ChatInfo.ReportServerLag)
function C_ChatInfo.ReportServerLag() end

