---@meta
--* GENERATED BY gemini-2.0-flash

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Container.GetContainerItemGems)
---@param containerIndex Enum.BagIndex
---@param slotIndex number
---@return number[] numGems
function C_Container.GetContainerItemGems(containerIndex, slotIndex) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Container.IsBagSlotFlagEnabledOnOtherBankBags)
---@param bagIndex Enum.BagIndex
---@param flagIndex number
---@return boolean isSet
function C_Container.IsBagSlotFlagEnabledOnOtherBankBags(bagIndex, flagIndex) end

