---@meta
--* GENERATED BY gemini-2.0-flash

---Returns a string description of what the current craft does.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCraftDescription)
---@param index number Number from 1 to X number of total crafts, where 1 is the top-most craft listed.
---@return string craftDescription Returns, for example, "Permanently enchant a two handed melee weapon to grant +25 Agility."
function GetCraftDescription(index) end

---Retrieves displayable information for the current craft.<br>
---This API only exists in Cata Classic and Classic Era.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCraftDisplaySkillLine)
---@return string? name The name of the active craft, or nil if the current craft has no displayable name.
---@return number? rank The player's current rank for the named craft, if applicable.
---@return number? maxRank The maximum rank for the named craft, if applicable.
function GetCraftDisplaySkillLine() end

---Returns information about a craft.<br>
---craftName, craftSubSpellName, craftType, numAvailable, isExpanded, trainingPointCost, requiredLevel = GetCraftInfo(index)
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCraftInfo)
---@param index number 1 to GetNumCrafts()
---@return string craftName Name of the item you can craft
---@return unknown craftSubSpellName
---@return string craftType "header" or how hard it is to create the item; trivial, easy, medium or optimal.
---@return number numAvailable This is the number of items you can create with the reagents you have in your inventory (the number is also shown in the UI).
---@return boolean? isExpanded Only applies to headers. Indicates whether they are expanded or contracted. Nil if not applicable.
---@return number? trainingPointCost This is the number of training points needed to train this skill if at a trainer. Nil if the craft window is not a trainer.
---@return number? requiredLevel The required level to train this skill if at a trainer. Nil if the craft window is not a trainer.
function GetCraftInfo(index) end

---Returns an itemLink for the specified trade skill item in the current active trade skill.<br>
---This API only exists in Cata Classic and Classic Era.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCraftItemLink)
---@param index number The index of the item in the current active trade skill.
---@return string? itemLink the corresponding item link for that item or nil, if the index is invalid or there is no active trade skill.
function GetCraftItemLink(index) end

---Gets the name displayed on the craft window.<br>
---This API only exists in Cata Classic and Classic Era.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCraftName)
---@return string craftName - It appears to return the localized name of for Enchanting, Poisons for Rogues, and Cooking?
function GetCraftName() end

---Returns the number of reagents required for a craft.<br>
---This API only exists in Cata Classic and Classic Era.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCraftNumReagents)
---@param index number Number from 1 to GetNumCrafts()
---@return number numRequiredReagents The number of required reagents for the craft.
function GetCraftNumReagents(index) end

---Returns the name, texture path, number required, and number have for a craft reagent.<br>
---This API only exists in Cata Classic and Classic Era.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCraftReagentInfo)
---@param index number starting at 1
---@param n number starting at 1
---@return string name Name of the reagent required.
---@return string texturePath Path to the required item texture.
---@return number numRequired Number of total required reagents.
---@return number numHave Number of total required reagents that the user has.
function GetCraftReagentInfo(index, n) end

---Returns a required reagent (as an itemLink) for a specific craftable item from the currently visible tradeskill window.<br>
---This API only exists in Cata Classic and Classic Era.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCraftReagentItemLink)
---@param index number index of the requested craft recipe, where 1 is the top-most listed recipe.
---@param n number index of the Nth reagent for the recipe, where 1 is the first reagent.
---@return string reagentLink itemLink for the requested reagent.
function GetCraftReagentItemLink(index, n) end

---Returns the EnchantLink for a craft.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCraftRecipeLink)
---@param index number The index of the item in the current active trade skill.
---@return string link An EnchantLink (color coded with href) which can be included in chat messages to show the reagents and the items the craft creates.
function GetCraftRecipeLink(index) end

---Tells the caller which, if any, crafting window is currently open.<br>
---This function is not quite the same as GetCraftDisplaySkillLine().<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCraftSkillLine)
---@param n number Not sure how this is used, but any number greater than zero seems to behave identically. Passing zero always results in a nil return value.
---@return string? currentCraftingWindow The name of the currently opened crafting window, or nil if no crafting window is open. This will be one of "Enchanting" or "Beast Training".
function GetCraftSkillLine(n) end

---Returns which rod is required for a craft, if any, when the enchanting screen is open.<br>
---Returns nil if no rods are required.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCraftSpellFocus)
---@param index number 1 to GetNumCrafts()
---@return string? catalystName Name of the rod.
---@return number? number1 Always 1 when a rod is required, meaning unknown.
function GetCraftSpellFocus(index) end

---Returns the number of crafts in the currently opened crafting window.<br>
---Usually used to loop through all available crafts to perfom API GetCraftInfo on them.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNumCrafts)
---@return number numberOfCrafts
function GetNumCrafts() end

