---@meta
--* GENERATED BY gemini-2.0-flash

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.AddCategoryFilter)
---@param category number
function C_Engraving.AddCategoryFilter(category) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.AddExclusiveCategoryFilter)
---@param category number
function C_Engraving.AddExclusiveCategoryFilter(category) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.CastRune)
---@param skillLineAbilityID number
function C_Engraving.CastRune(skillLineAbilityID) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.ClearAllCategoryFilters)
function C_Engraving.ClearAllCategoryFilters() end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.ClearCategoryFilter)
---@param category number
function C_Engraving.ClearCategoryFilter(category) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.ClearExclusiveCategoryFilter)
function C_Engraving.ClearExclusiveCategoryFilter() end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.EnableEquippedFilter)
---@param enabled boolean
function C_Engraving.EnableEquippedFilter(enabled) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.GetCurrentRuneCast)
---@return EngravingData? engravingInfo
function C_Engraving.GetCurrentRuneCast() end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.GetEngravingModeEnabled)
---@return boolean enabled
function C_Engraving.GetEngravingModeEnabled() end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.GetExclusiveCategoryFilter)
---@return number? category
function C_Engraving.GetExclusiveCategoryFilter() end

---Returns the number of runes known for a given equipment slot.<br>
---known, max = C_Engraving.GetNumRunesKnown([equipmentSlot])
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.GetNumRunesKnown)
---@param equipmentSlot number?
---@return number known
---@return number max
function C_Engraving.GetNumRunesKnown(equipmentSlot) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.GetRuneCategories)
---@param shouldFilter boolean
---@param ownedOnly boolean
---@return number[] categories
function C_Engraving.GetRuneCategories(shouldFilter, ownedOnly) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.GetRuneForEquipmentSlot)
---@param equipmentSlot number
---@return EngravingData? engravingInfo
function C_Engraving.GetRuneForEquipmentSlot(equipmentSlot) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.GetRuneForInventorySlot)
---@param containerIndex number
---@param slotIndex number
---@return EngravingData? engravingInfo
function C_Engraving.GetRuneForInventorySlot(containerIndex, slotIndex) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.GetRunesForCategory)
---@param category number
---@param ownedOnly boolean
---@return EngravingData[] engravingInfo
function C_Engraving.GetRunesForCategory(category, ownedOnly) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.HasCategoryFilter)
---@param category number
---@return boolean result
function C_Engraving.HasCategoryFilter(category) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.IsEngravingEnabled)
---@return boolean value
function C_Engraving.IsEngravingEnabled() end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.IsEquipmentSlotEngravable)
---@param equipmentSlot number
---@return boolean result
function C_Engraving.IsEquipmentSlotEngravable(equipmentSlot) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.IsEquippedFilterEnabled)
---@return boolean value
function C_Engraving.IsEquippedFilterEnabled() end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.IsInventorySlotEngravable)
---@param containerIndex number
---@param slotIndex number
---@return boolean result
function C_Engraving.IsInventorySlotEngravable(containerIndex, slotIndex) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.IsInventorySlotEngravableByCurrentRuneCast)
---@param containerIndex number
---@param slotIndex number
---@return boolean result
function C_Engraving.IsInventorySlotEngravableByCurrentRuneCast(containerIndex, slotIndex) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.IsKnownRuneSpell)
---@param spellID number
---@return boolean result
function C_Engraving.IsKnownRuneSpell(spellID) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.IsRuneEquipped)
---@param skillLineAbilityID number
---@return boolean result
function C_Engraving.IsRuneEquipped(skillLineAbilityID) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.RefreshRunesList)
function C_Engraving.RefreshRunesList() end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.SetEngravingModeEnabled)
---@param enabled boolean
function C_Engraving.SetEngravingModeEnabled(enabled) end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Engraving.SetSearchFilter)
---@param filter string
function C_Engraving.SetSearchFilter(filter) end

