---@meta
--* GENERATED BY gemini-2.0-flash

---Collapses a faction header row.<br>
---The UPDATE_FACTION event is fired after the change since faction indexes will have been shifted around.
---[Documentation](https://warcraft.wiki.gg/wiki/API_CollapseFactionHeader)
---@param rowIndex number The row index of the header to collapse (Specifying a non-header row can have unpredictable results).
function CollapseFactionHeader(rowIndex) end

---Expands a faction header row.<br>
---The UPDATE_FACTION event is fired after the change since faction indexes will have been shifted around.
---[Documentation](https://warcraft.wiki.gg/wiki/API_ExpandFactionHeader)
---@param rowIndex number The row index of the header to expand (Specifying a non-header row can have unpredictable results).
function ExpandFactionHeader(rowIndex) end

---Toggles the At War status for a faction.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_FactionToggleAtWar)
---@param rowIndex number The row index of the faction to toggle the At War status for.
function FactionToggleAtWar(rowIndex) end

---Returns info for a faction.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetFactionInfo)
---@param factionIndex number Index from the currently displayed row in the player's reputation pane, including headers but excluding factions that are hidden because their parent header is collapsed.
---@return string name Name of the faction
---@return string description Description as shown in the detail pane that appears when you click on the faction row
---@return number standingID <a href="/wiki/API_TYPE_StandingId" class="mw-redirect" title="API TYPE StandingId">StandingId</a> representing the current standing (eg. 4 for Neutral, 5 for Friendly).
---@return number barMin Minimum reputation since beginning of Neutral to reach the current standing.
---@return number barMax Maximum reputation since the beginning of Neutral before graduating to the next standing.
---@return number barValue Total reputation earned with the faction versus 0 at the beginning of Neutral.
---@return boolean atWarWith True if the player is at war with the faction
---@return boolean canToggleAtWar True if the player can toggle the "<a href="/wiki/At_War" title="At War">At War</a>" checkbox
---@return boolean isHeader True if the faction is a header (collapsible group title)
---@return boolean isCollapsed True if the faction is a header <b>and</b> is currently collapsed
---@return boolean hasRep True if the faction is a header <b>and</b> has its own reputation (eg. The Tillers)
---@return boolean isWatched True if the "Show as Experience Bar" checkbox for the faction is currently checked
---@return boolean isChild True if the faction is a second-level header (eg. Sholazar Basin) <b>or</b> is the child of a second-level header (eg. The Oracles)
---@return number factionID Unique <a href="/wiki/FactionID" title="FactionID">FactionID</a>.
---@return boolean hasBonusRepGain True if the player has purchased a <a href="/wiki/Grand_Commendation" title="Grand Commendation">Grand Commendation</a> to unlock bonus reputation gains with this faction
---@return boolean canSetInactive
function GetFactionInfo(factionIndex) end

---Returns info for a faction.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetFactionInfo)
---@param factionID number FactionID
---@return string name Name of the faction
---@return string description Description as shown in the detail pane that appears when you click on the faction row
---@return number standingID <a href="/wiki/API_TYPE_StandingId" class="mw-redirect" title="API TYPE StandingId">StandingId</a> representing the current standing (eg. 4 for Neutral, 5 for Friendly).
---@return number barMin Minimum reputation since beginning of Neutral to reach the current standing.
---@return number barMax Maximum reputation since the beginning of Neutral before graduating to the next standing.
---@return number barValue Total reputation earned with the faction versus 0 at the beginning of Neutral.
---@return boolean atWarWith True if the player is at war with the faction
---@return boolean canToggleAtWar True if the player can toggle the "<a href="/wiki/At_War" title="At War">At War</a>" checkbox
---@return boolean isHeader True if the faction is a header (collapsible group title)
---@return boolean isCollapsed True if the faction is a header <b>and</b> is currently collapsed
---@return boolean hasRep True if the faction is a header <b>and</b> has its own reputation (eg. The Tillers)
---@return boolean isWatched True if the "Show as Experience Bar" checkbox for the faction is currently checked
---@return boolean isChild True if the faction is a second-level header (eg. Sholazar Basin) <b>or</b> is the child of a second-level header (eg. The Oracles)
---@return number factionID Unique <a href="/wiki/FactionID" title="FactionID">FactionID</a>.
---@return boolean hasBonusRepGain True if the player has purchased a <a href="/wiki/Grand_Commendation" title="Grand Commendation">Grand Commendation</a> to unlock bonus reputation gains with this faction
---@return boolean canSetInactive
function GetFactionInfoByID(factionID) end

---Returns the guild name and faction standing of the player.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetGuildFactionInfo)
---@return string guildName The name of the guild the unit is in or the localized word of "Guild"
---@return string description A localized faction description.
---@return number standingID players faction standing (see StandingId)
---@return number barMin
---@return number barMax
---@return number barValue
function GetGuildFactionInfo() end

---Returns the number of lines in the faction display.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNumFactions)
---@return number numberOfFactions The number of lines in your faction display (based on known factions and expanded/collapsed faction lines)
function GetNumFactions() end

---Returns info for the currently watched faction.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetWatchedFactionInfo)
---@return string? name The name of the faction curretly being watched, nil if no faction is being watched.
---@return number? standing The StandingId with the faction.
---@return number? min The minimum bound for the current standing.
---@return number? max The maximum bound for the current standing.
---@return number? value The current faction level, within the bounds.
---@return number? factionID Unique numeric identifier for the faction.
function GetWatchedFactionInfo() end

---Returns true if the specified faction is marked inactive.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsFactionInactive)
---@param index number index of the faction within the faction list, ascending from 1.
---@return boolean inactive 1 if the faction is flagged as inactive, nil otherwise.
function IsFactionInactive(index) end

---Flags the specified faction as active in the reputation window.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Reputation.SetFactionActive)
---@param index number The index of the faction to mark active, ascending from 1.
function C_Reputation.SetFactionActive(index) end

---Flags the specified faction as inactive in the reputation window.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Reputation.SetFactionActive)
---@param index number The index of the faction to mark inactive, ascending from 1.
function C_Reputation.SetFactionActive(index) end

---Watches a faction in the reputation window.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_SetWatchedFactionIndex)
---@param index number The index of the faction to watch, ascending from 1; out-of-range values will clear the watched faction.
function SetWatchedFactionIndex(index) end

