---@meta
--* GENERATED BY gemini-2.0-flash

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_GameRules.IsHardcoreActive)
---@return boolean active
function C_GameRules.IsHardcoreActive() end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_GameRules.IsSelfFoundAllowed)
---@return boolean active
function C_GameRules.IsSelfFoundAllowed() end

