---@meta
--* GENERATED BY gemini-2.0-flash

---Cancels your current tracking buff (skills like Find Minerals and Track Humanoids).<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_CancelTrackingBuff)
function CancelTrackingBuff() end

---Returns the player's currently casting spell.<br>
---In Classic only casting information for the player is available.
---[Documentation](https://warcraft.wiki.gg/wiki/API_CastingInfo)
---@return string name The name of the spell.
---@return string text The name to be displayed.
---@return number texture FileID
---@return number startTime Specifies when casting began in milliseconds (corresponds to GetTime()*1000).
---@return number endTime Specifies when casting will end in milliseconds (corresponds to GetTime()*1000).
---@return boolean isTradeSkill
---@return string castID e.g. "Cast-3-4479-0-1318-2053-000014AD63"
---@return boolean? notInterruptible This is always nil.
---@return number spellID
function CastingInfo() end

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_ConfirmBinder)
function ConfirmBinder() end

---Returns true if the item held by the cursor can be equipped in the specified (equipment) inventory slot.<br>
---This function was deprecated in patch 10.0.0 and will be removed in patch 11.0.2.
---[Documentation](https://warcraft.wiki.gg/wiki/API_CursorCanGoInSlot)
---@param invSlot number Inventory slot to query
---@return boolean 1 if the thing currently on the cursor can go into the specified slot, nil otherwise.
function CursorCanGoInSlot(invSlot) end

---Fills a table with localized male or female class names.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_FillLocalizedClassList)
---@param tbl table The table you want to be filled with the data.
---@param isFemale boolean? If the table should be filled with female class names.
---@return table The same table argument you passed.
function FillLocalizedClassList(tbl, isFemale) end

---Replaces `GMSubmitBug`.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_UserFeedback.SubmitBug)
---@param bugInfo string
---@param suppressNotification? boolean
---@return boolean success
function C_UserFeedback.SubmitBug(bugInfo, suppressNotification) end

---Replaces `GMSubmitSuggestion`.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_UserFeedback.SubmitSuggestion)
---@param suggestion string
---@return boolean success
function C_UserFeedback.SubmitSuggestion(suggestion) end

---Returns the percentage of target's armory your physical attacks ignore due to armor penetration.<br>
---This API only exists in Cata Classic and Classic Era.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetArmorPenetration)
---@return number armorPen - Percent of armor ignored by your physical attacks.
function GetArmorPenetration() end

---Returns the index of the current screen resolution.<br>
---This value will be the index of one of the values yielded by <a href="/wiki/API_GetScreenResolutions" title="API GetScreenResolutions">GetScreenResolutions()</a>.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCurrentResolution)
---@return number index
function GetCurrentResolution() end

---Indicates which [Eclipse] state the player is moving towards.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetEclipseDirection)
---@return string direction # "moon", "sun", or "none"
function GetEclipseDirection() end

---Returns your current expertise reduction to chance to be dodged or parried, in percent.<br>
---Replaced by <a href="/wiki/API_GetExpertise" title="API GetExpertise">GetExpertise</a> in Patch 5.0.4.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetExpertisePercent)
---@return number expertisePercent # Percentage reduction in dodge and parry chances for swings with your main hand weapon.
---@return number offhandExpertisePercent # Percentage reduction in dodge and parry chances for swings with your offhand weapon.
function GetExpertisePercent() end

---Returns info for Quick join invites.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_PartyInfo.GetInviteReferralInfo)
---@param inviteGUID string
---@return string outReferredByGuid
---@return string outReferredByName
---@return Enum.PartyRequestJoinRelation outRelationType
---@return boolean outIsQuickJoin
---@return string outClubId
function C_PartyInfo.GetInviteReferralInfo(inviteGUID) end

---Returns a list of available preset windowed screen resolutions.<br>
---Returns the list that appears in the resolution dropdown only while windowed mode is applied.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetScreenResolutions)
---@return string ... resolutionN An available screen resolution as ___x___ (width .. "x" .. height).
function GetScreenResolutions() end

---Returns if the player is melee attacking the specified unit.<br>
---This API only exists in Cata Classic and Classic Era.
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsPlayerAttacking)
---@param unit string The unit to check.
---@return boolean isAttacking True if the player is attacking the unit, false otherwise.
function IsPlayerAttacking(unit) end

---Sets the screen resolution.<br>
---This API only exists in Cata Classic and Classic Era.
---[Documentation](https://warcraft.wiki.gg/wiki/API_SetScreenResolution)
---@param index number? This value specifies the new screen resolution, it must be the index of one of the values yielded by GetScreenResolutions(). Passing nil will default this argument to 1, the lowest resolution available
function SetScreenResolution(index) end

---Returns whether the player would have been able to know the unit's exact health value in the original game release.<br>
---This API only exists in Cata Classic and Classic Era.
---[Documentation](https://warcraft.wiki.gg/wiki/API_ShouldKnowUnitHealth)
---@param unit string UnitId
---@return boolean shouldKnowUnitHealth
function ShouldKnowUnitHealth(unit) end

---Enables or disables display of your cloak.<br>
---This API only exists in Cata Classic and Classic Era. Removed in Patch 7.0.3.
---[Documentation](https://warcraft.wiki.gg/wiki/API_ShowCloak)
---@param flag boolean whether the cloak should be shown
function ShowCloak(flag) end

---Enables or disables display of your helm.<br>
---This API only exists in Cata Classic and Classic Era. Removed in Patch 7.0.3.
---[Documentation](https://warcraft.wiki.gg/wiki/API_ShowHelm)
---@param flag boolean whether the helm should be shown
function ShowHelm(flag) end

---Returns if the player is showing his cloak.<br>
---This API only exists in Cata Classic and Classic Era. Removed in Patch 7.0.3.
---[Documentation](https://warcraft.wiki.gg/wiki/API_ShowingCloak)
---@return boolean isShowingCloak
function ShowingCloak() end

---Returns if the player is showing his helm.<br>
---This API only exists in Cata Classic and Classic Era. Removed in Patch 7.0.3.
---[Documentation](https://warcraft.wiki.gg/wiki/API_ShowingHelm)
---@return boolean isShowingHelm
function ShowingHelm() end

