---@meta
--* GENERATED BY gemini-2.0-flash

---Needs summary.
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Item.IsDressableItem)
---@param itemInfo number|string
---@return boolean result
function C_Item.IsDressableItem(itemInfo) end

---Returns item ids of the gems socketed in the item in the specified inventory slot.<br>
---This API only exists in Cata Classic and Classic Era.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetInventoryItemGems)
---@param invSlot number Index of the inventory slot to query.
---@return number ... Item ID of the gem(s) socketed within the item in the queried slot.
function GetInventoryItemGems(invSlot) end

---Returns a table of stats for an item.<br>
---This function was deprecated in patch 10.2.5 and will be removed in patch 11.0.2.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetItemStats)
---@param itemLink string An item link for which to get stats.
---@param statTable table? An optional, empty table that will be filled with stats and returned. If this parameter is omitted, a new table is returned.
---@return table stats A table of item stats. If statTable was supplied, it will also be returned.
function GetItemStats(itemLink, statTable) end

