---@meta
--* GENERATED BY gemini-2.0-flash

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Macro.GetNumIcons)
---@return number numIcons
function C_Macro.GetNumIcons() end

