---@meta
--* GENERATED BY gemini-2.0-flash

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Map.GetBountySetIDForMap)
---@param uiMapID number
---@return number bountySetID
function C_Map.GetBountySetIDForMap(uiMapID) end

