---@meta
--* GENERATED BY gemini-2.0-flash

---Returns info for a merchant item.<br>
---This function was deprecated in patch 11.0.5 and will be removed in the next expansion.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetMerchantItemInfo)
---@param index number The index of the item in the merchant's inventory
---@return string name The name of the item
---@return number texture The texture that represents the item's icon
---@return number price The price of the item (in copper)
---@return number quantity The quantity that will be purchased (the batch size, e.g. 5 for vials)
---@return number numAvailable The number of this item that the merchant has in stock. -1 for unlimited stock.
---@return boolean isPurchasable
---@return boolean isUsable True if the player can use this item, false otherwise
---@return boolean extendedCost True if the item has extended (PvP) cost info, false otherwise
---@return number? currencyID
---@return number? spellID
function GetMerchantItemInfo(index) end

