---@meta
--* GENERATED BY gemini-2.0-flash


C_BattleNet = {}
C_AreaPoiInfo = {}
C_BarberShop = {}
C_ChatInfo = {}
C_Container = {}
C_Engraving = {}
C_GameRules = {}
C_Item = {}
C_LootHistory = {}
C_Macro = {}
C_Map = {}
C_PlayerInfo = {}
C_PvP = {}
C_QuestLog = {}
C_Reforge = {}
C_Seasons = {}
C_StorePublic = {}
C_UIWidgetManager = {}
C_PartyInfo = {}
C_UserFeedback = {}
C_SuperTrack = {}
C_Spell = {}
C_SpellBook = {}
C_CurrencyInfo = {}
C_Reputation = {}
C_UnitAuras = {}


