---@meta
--* GENERATED BY gemini-2.0-flash

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_PlayerInfo.IsXPUserDisabled)
---@return boolean isDisabled
function C_PlayerInfo.IsXPUserDisabled() end

