---@meta
--* GENERATED BY gemini-2.0-flash

---Returns the ID of the season that is active on the current realm.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Seasons.GetActiveSeason)
---@return Enum.SeasonID? seasonID The currently active season ID, if one is active.
function C_Seasons.GetActiveSeason() end

---Returns true if the player is on a seasonal realm.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Seasons.HasActiveSeason)
---@return boolean active # true if the player is on a seasonal realm, otherwise false.
function C_Seasons.HasActiveSeason() end

