---@meta
--* GENERATED BY gemini-2.0-flash

---Collapses a header in the skills window.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_CollapseSkillHeader)
---@param index number The index of a line in the skills window, can be a header or skill line belonging to a header. Index 0 ("All") will collapse all headers.
function CollapseSkillHeader(index) end

---Collapses a header in the trainer window, hiding all spells below it.<br>
---Note that indices are affected by the trainer filter, see GetTrainerServiceTypeFilter() and SetTrainerServiceTypeFilter()<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_CollapseTrainerSkillLine)
---@param index number The index of a line in the trainer window (if the supplied index is not a header, an error is produced). Index 0 ("All") will collapse all headers.
function CollapseTrainerSkillLine(index) end

---Expands a header in the skills window.<br>
---This API only exists in Cata Classic and Classic Era.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_ExpandSkillHeader)
---@param index number The index of a line in the skills window. Index 0 ("All") will expand all headers.
function ExpandSkillHeader(index) end

---Expands a header in the trainer window, showing all spells below it.<br>
---This API only exists in Cata Classic and Classic Era.
---[Documentation](https://warcraft.wiki.gg/wiki/API_ExpandTrainerSkillLine)
---@param index number The index of a line in the trainer window. Index 0 ("All") will expand all headers.
function ExpandTrainerSkillLine(index) end

---Returns the number of skill lines in the skill window, including headers.<br>
---This API only exists in Cata Classic and Classic Era. Removed in Patch 4.0.1.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNumSkillLines)
---@return number numberOfSkillLines
function GetNumSkillLines() end

---Returns the currently selected skill line.<br>
---This API only exists in Cata Classic and Classic Era. Removed in Patch 4.0.1.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSelectedSkill)
---@return number skillIndex
function GetSelectedSkill() end

---Returns information on a skill line/header.<br>
---This API only exists in Cata Classic and Classic Era.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSkillLineInfo)
---@param index number The index of a line in the skills window, can be a header or skill line.
---@return string skillName Name of the skill line.
---@return number header Returns 1 if the line is a header, nil otherwise.
---@return number isExpanded Returns 1 if the line is a header and expanded, nil otherwise.
---@return number skillRank The current rank for the skill, 0 if not applicable.
---@return number numTempPoints Temporary points for the current skill.
---@return number skillModifier Skill modifier value for the current skill.
---@return number skillMaxRank The maximum rank for the current skill.
---@return number isAbandonable Returns 1 if this skill can be unlearned, nil otherwise.
---@return number stepCost Returns 1 if skill can be learned, nil otherwise.
---@return number rankCost Returns 1 if skill can be trained, nil otherwise.
---@return number minLevel Minimum level required to learn this skill.
---@return number skillCostType unknown
---@return string skillDescription Localized skill description text
function GetSkillLineInfo(index) end

---Selects a skill line in the skill window.<br>
---This API only exists in Cata Classic and Classic Era. Removed in Patch 4.0.1.
---[Documentation](https://warcraft.wiki.gg/wiki/API_SetSelectedSkill)
---@param index number The index of a line in the skills window. Does nothing when used on a header.
function SetSelectedSkill(index) end

