---@meta
--* GENERATED BY gemini-2.0-flash

---Returns true if the player character knows the spell.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_DoesSpellExist)
---@param spellName string
---@return boolean spellExists
function DoesSpellExist(spellName) end

---Needs summary.<br>
---For the level you put in, it returns the ID of the spell that will become available.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetCurrentLevelSpells)
---@param level number
---@return unknown id The ID of the spell you will learn at that level.
function GetCurrentLevelSpells(level) end

---Returns the number of tabs in the spellbook.<br>
---This function was deprecated in patch 11.0.0 and will be removed in patch 11.0.2. Replaced by C_SpellBook.GetNumSpellBookSkillLines.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetNumSpellTabs)
---@deprecated
---@return number numTabs - number of ability tabs in the player's spellbook (e.g. 4 -- "General", "Arcane", "Fire", "Frost")
function GetNumSpellTabs() end

---Returns true if a (pet) spell is autocastable.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellAutocast)
---@param spellName string|number the name of the spell or the offset (position) of spell in spellbook.
---@param bookType string Either BOOKTYPE_SPELL ("spell") or BOOKTYPE_PET ("pet").
---@return number? autocastable whether a spell is autocastable. Returns 1 if the spell is autocastable, nil otherwise.
---@return number? autostate whether a spell is currently set to autocast. Returns 1 if the spell is currently set for autocast, nil otherwise.
function GetSpellAutocast(spellName, bookType) end

---Returns info for a spellbook item.<br>
---Replaced by C_SpellBook.GetSpellBookItemInfo in Patch 11.0.0.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellBoo
---@deprecatedkItemInfo)
---@param spellName string|number the name of the spell or the offset (position) of spell in spellbook.
---@param bookType string? Either BOOKTYPE_SPELL ("spell") or BOOKTYPE_PET ("pet").
---@return string? spellType The type of the spell: ["SPELL", "FUTURESPELL", "PETACTION", "FLYOUT"]
---@return number? id For SPELL and FUTURESPELL, the SpellID used in GetSpellInfo(); For PETACTION, the ActionID used in C_ActionBar.HasPetActionButtons(); For FLYOUT, the FlyoutID used in GetFlyoutInfo()
function GetSpellBookItemInfo(spellName, bookType) end

---Returns the name of a spellbook item.<br>
---This function was deprecated in patch 11.0.0 and will be removed in patch 11.0.2.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellBookItemName)
---@deprecated
---@param spellName string Requires the spell to be in your Spellbook.
---@return string spellName Name of the spell as it appears in the spell book, e.g. "Lesser Heal"
---@return string spellSubName The spell rank or sub type, e.g. "Grand Master", "Racial Passive". This can be an empty string.
---@return number spellID
function GetSpellBookItemName(spellName) end

---Returns the name of a spellbook item.<br>
---This function was deprecated in patch 11.0.0 and will be removed in patch 11.0.2.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellBookItemName)
---@deprecated
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
---@return string spellName Name of the spell as it appears in the spell book, e.g. "Lesser Heal"
---@return string spellSubName The spell rank or sub type, e.g. "Grand Master", "Racial Passive". This can be an empty string.
---@return number spellID
function GetSpellBookItemName(index, bookType) end

---Returns the icon texture of a spellbook item.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellBookItemTexture)
---@param spell number|string
---@param index number
---@param bookType string
---@return number? icon
function GetSpellBookItemTexture(spell, index, bookType) end

---Returns information about the charges of a charge-accumulating player ability.<br>
---This function was deprecated in patch 11.0.0 and will be removed in patch 11.0.2.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellCharges)
---@deprecated
---@param spell number|string Spell ID or Name. When passing a name requires the spell to be in your Spellbook.
---@return number currentCharges The number of charges of the ability currently available.
---@return number maxCharges The maximum number of charges the ability may have available.
---@return number cooldownStart Time (per GetTime) at which the last charge cooldown began, or 2^32 / 1000 - cooldownDuration if the spell is not currently recharging.
---@return number cooldownDuration Time (in seconds) required to gain a charge.
---@return number chargeModRate The rate at which the charge cooldown widget's animation should be updated.
function GetSpellCharges(spell) end

---Returns information about the charges of a charge-accumulating player ability.<br>
---This function was deprecated in patch 11.0.0 and will be removed in patch 11.0.2.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellCharges)
---@deprecated
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
---@return number currentCharges The number of charges of the ability currently available.
---@return number maxCharges The maximum number of charges the ability may have available.
---@return number cooldownStart Time (per GetTime) at which the last charge cooldown began, or 2^32 / 1000 - cooldownDuration if the spell is not currently recharging.
---@return number cooldownDuration Time (in seconds) required to gain a charge.
---@return number chargeModRate The rate at which the charge cooldown widget's animation should be updated.
function GetSpellCharges(index, bookType) end

---Returns the cooldown info of a spell.<br>
---This function was deprecated in patch 11.0.0 and will be removed in patch 11.0.2.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellCooldown)
---@deprecated
---@param spell number|string Spell ID or Name. When passing a name requires the spell to be in your Spellbook.
---@return number startTime The time when the cooldown started (as returned by GetTime()); zero if no cooldown; current time if (enabled == 0).
---@return number duration Cooldown duration in seconds, 0 if spell is ready to be cast.
---@return number enabled 0 if the spell is active (Stealth, Shadowmeld, Presence of Mind, etc) and the cooldown will begin as soon as the spell is used/cancelled; 1 otherwise.
---@return number modRate The rate at which the cooldown widget's animation should be updated.
function GetSpellCooldown(spell) end

---Returns the cooldown info of a spell.<br>
---This function was deprecated in patch 11.0.0 and will be removed in patch 11.0.2.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellCooldown)
---@deprecated
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
---@return number startTime The time when the cooldown started (as returned by GetTime()); zero if no cooldown; current time if (enabled == 0).
---@return number duration Cooldown duration in seconds, 0 if spell is ready to be cast.
---@return number enabled 0 if the spell is active (Stealth, Shadowmeld, Presence of Mind, etc) and the cooldown will begin as soon as the spell is used/cancelled; 1 otherwise.
---@return number modRate The rate at which the cooldown widget's animation should be updated.
function GetSpellCooldown(index, bookType) end

---Returns the number of times a spell can be cast. Generally used for spells limited by the number of available item reagents.<br>
---This function was deprecated in patch 11.0.0 and will be removed in patch 11.0.2.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellCount)
---@deprecated
---@param spell number|string Spell ID or Name. When passing a name requires the spell to be in your Spellbook.
---@return number numCasts
function GetSpellCount(spell) end

---Returns the number of times a spell can be cast. Generally used for spells limited by the number of available item reagents.<br>
---This function was deprecated in patch 11.0.0 and will be removed in patch 11.0.2.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellCount)
---@deprecated
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
---@return number numCasts
function GetSpellCount(index, bookType) end

---Returns the spell description.<br>
---This function was deprecated in patch 11.0.0 and will be removed in patch 11.0.2.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellDescription)
---@deprecated
---@param spellID number Not readily available on function call, see SpellMixin:ContinueOnSpellLoad.
---@return string desc
function GetSpellDescription(spellID) end

---Returns spell info.<br>
---name, rank, icon, castTime, minRange, maxRange, spellID, originalIcon = GetSpellInfo(spell)<br>
---name, rank, icon, castTime, minRange, maxRange, spellID, originalIcon = GetSpellInfo(index, bookType)
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellInfo)
---@param spell number|string Spell ID or Name. When passing a name requires the spell to be in your Spellbook.
---@return string name The localized name of the spell.
---@return string? rank Always returns nil. Refer to GetSpellSubtext() for retrieving the rank of spells on Classic.
---@return number icon FileID - The spell icon texture.
---@return number castTime Cast time in milliseconds, or 0 for instant spells.
---@return number minRange Minimum range of the spell, or 0 if not applicable.
---@return number maxRange Maximum range of the spell, or 0 if not applicable.
---@return number spellID The ID of the spell.
---@return number originalIcon FileID - The original icon texture for this spell.
function GetSpellInfo(spell) end

---Returns spell info.<br>
---name, rank, icon, castTime, minRange, maxRange, spellID, originalIcon = GetSpellInfo(spell)<br>
---name, rank, icon, castTime, minRange, maxRange, spellID, originalIcon = GetSpellInfo(index, bookType)
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellInfo)
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
---@return string name The localized name of the spell.
---@return string? rank Always returns nil. Refer to GetSpellSubtext() for retrieving the rank of spells on Classic.
---@return number icon FileID - The spell icon texture.
---@return number castTime Cast time in milliseconds, or 0 for instant spells.
---@return number minRange Minimum range of the spell, or 0 if not applicable.
---@return number maxRange Maximum range of the spell, or 0 if not applicable.
---@return number spellID The ID of the spell.
---@return number originalIcon FileID - The original icon texture for this spell.
function GetSpellInfo(index, bookType) end

---Returns the hyperlink for a spell.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellLink)
---@param spell number|string Spell ID or Name. When passing a name requires the spell to be in your Spellbook.
---@return string link : spellLink
---@return number spellID
function GetSpellLink(spell) end

---Returns the hyperlink for a spell.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellLink)
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
---@return string link : spellLink
---@return number spellID
function GetSpellLink(index, bookType) end

---Returns information about a loss-of-control cooldown affecting a spell.<br>
---start, duration = GetSpellLossOfControlCooldown(spellSlot[, bookType] or spellName or spellID)
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellLossOfControlCooldown)
---@param spellSlot number spell book slot index, ascending from 1.
---@param bookType string spell book type token, e.g. "spell" from player's spell book.
---@return number start time at which the loss-of-control cooldown began, per GetTime.
---@return number duration duration of the loss-of-control cooldown in seconds; 0 if the spell is not currently affected by a loss-of-control cooldown.
function GetSpellLossOfControlCooldown(spellSlot, bookType) end

---Returns information about a loss-of-control cooldown affecting a spell.<br>
---start, duration = GetSpellLossOfControlCooldown(spellSlot[, bookType] or spellName or spellID)
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellLossOfControlCooldown)
---@param spellName string name of a spell in the player's spell book.
---@return number start time at which the loss-of-control cooldown began, per GetTime.
---@return number duration duration of the loss-of-control cooldown in seconds; 0 if the spell is not currently affected by a loss-of-control cooldown.
function GetSpellLossOfControlCooldown(spellName) end

---Returns information about a loss-of-control cooldown affecting a spell.<br>
---start, duration = GetSpellLossOfControlCooldown(spellSlot[, bookType] or spellName or spellID)
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellLossOfControlCooldown)
---@param spellID number spell ID of a spell accessible to the player.
---@return number start time at which the loss-of-control cooldown began, per GetTime.
---@return number duration duration of the loss-of-control cooldown in seconds; 0 if the spell is not currently affected by a loss-of-control cooldown.
function GetSpellLossOfControlCooldown(spellID) end

---Returns resource cost info for a spell.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellPowerCost)
---@param spell number|string Spell ID or Name. When passing a name requires the spell to be in your Spellbook.
---@return table[] costs
function GetSpellPowerCost(spell) end

---Returns resource cost info for a spell.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellPowerCost)
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
---@return table[] costs
function GetSpellPowerCost(index, bookType) end

---Returns info for the specified spellbook tab.<br>
---This function was deprecated in patch 11.0.0 and will be removed in patch 11.0.2.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellTabInfo)
---@deprecated
---@param tabIndex number The index of the tab, ascending from 1.
---@return string name The name of the spell line (General, Shadow, Fury, etc.)
---@return string texture The texture path for the spell line's icon
---@return number offset Number of spell book entries before this tab (one less than index of the first spell book item in this tab)
---@return number numSlots The number of spell entries in this tab.
---@return boolean isGuild true for Guild Perks, false otherwise
---@return number offspecID 0 if the tab contains spells you can cast (general/specialization/trade skill/etc); or specialization ID of the specialization this tab is showing the spells of.
function GetSpellTabInfo(tabIndex) end

---Returns the icon texture of a spell.<br>
---This function was deprecated in patch 11.0.0 and will be removed in patch 11.0.2.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellTexture)
---@deprecated
---@param spell number|string Spell ID or Name. When passing a name requires the spell to be in your Spellbook.
---@return number icon icon texture used by the spell.
function GetSpellTexture(spell) end

---Returns the icon texture of a spell.<br>
---This function was deprecated in patch 11.0.0 and will be removed in patch 11.0.2.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetSpellTexture)
---@deprecated
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
---@return number icon icon texture used by the spell.
function GetSpellTexture(index, bookType) end

---Returns true if a spellbook item is the "Auto Attack" spell.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsAttackSpell)
---@param spellName string The spell name to test.
---@return number isAttack Returns 1 if the spell is the "Attack" spell, nil otherwise
function IsAttackSpell(spellName) end

---Checks if a spell is an auto attack.
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Spell.IsAutoAttackSpell)
---@param spellID number
---@return boolean
function C_Spell.IsAutoAttackSpell(spellID) end

---Checks if a spell is a ranged auto attack.
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Spell.IsRangedAutoAttackSpell)
---@param spellID number
---@return boolean
function C_Spell.IsRangedAutoAttackSpell(spellID) end

---Checks if a spellbook item is an auto attack.
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_SpellBook.IsAutoAttackSpellBookItem)
---@param spellID number
---@return boolean
function C_SpellBook.IsAutoAttackSpellBookItem(spellID) end

---Checks if a spellbook item is a ranged auto attack.
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_SpellBook.IsRangedAutoAttackSpellBookItem)
---@param spellID number
---@return boolean
function C_SpellBook.IsRangedAutoAttackSpellBookItem(spellID) end

---Returns true if the specified spell ID is currently being casted or queued.<br>
---If spell is current then action bar indicates its slot with highlighted frame.
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsCurrentSpell)
---@param spellID number - spell ID to query.
---@return boolean - true if currently being casted or queued, false otherwise. isCurrent
function IsCurrentSpell(spellID) end

---Returns true if the specified spell is a passive ability.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsPassiveSpell)
---@param spellId number|number spellId or index
---@param bookType string? Either BOOKTYPE_SPELL ("spell") or BOOKTYPE_PET ("pet"). "spell" is linked to your General Spellbook tab.
---@return number? isPassive 1 if the spell is passive, nil otherwise.
function IsPassiveSpell(spellId, bookType) end

---Checks if a spell is an auto attack.
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Spell.IsAutoAttackSpell)
---@param spellID number
---@return boolean
function C_Spell.IsAutoAttackSpell(spellID) end

---Checks if a spell is a ranged auto attack.
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Spell.IsRangedAutoAttackSpell)
---@param spellID number
---@return boolean
function C_Spell.IsRangedAutoAttackSpell(spellID) end

---Checks if a spellbook item is an auto attack.
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_SpellBook.IsAutoAttackSpellBookItem)
---@param spellID number
---@return boolean
function C_SpellBook.IsAutoAttackSpellBookItem(spellID) end

---Checks if a spellbook item is a ranged auto attack.
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_SpellBook.IsRangedAutoAttackSpellBookItem)
---@param spellID number
---@return boolean
function C_SpellBook.IsRangedAutoAttackSpellBookItem(spellID) end

---Checks if a spellbook item is passive.
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_SpellBook.IsSpellBookItemPassive)
---@param spellID number
---@return boolean
function C_SpellBook.IsSpellBookItemPassive(spellID) end

---Checks if a spell is passive.
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Spell.IsSpellPassive)
---@param spellID number
---@return boolean
function C_Spell.IsSpellPassive(spellID) end

---Returns 1 if the player is in range to use the specified spell on the target unit, 0 otherwise.<br>
---Takes into account talents, and can be used to determine the approximate distance to your raid members.
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsSpellInRange)
---@param spellName string The localized spell name. The player must know the spell.
---@param unit string UnitId The unit to use as a target for the spell.
---@return number? inRange 1 if the target is in range of the spell, 0 if the target is not in range of the spell, nil if the provided arguments were invalid or inapplicable.
function IsSpellInRange(spellName, unit) end

---Returns 1 if the player is in range to use the specified spell on the target unit, 0 otherwise.<br>
---Takes into account talents, and can be used to determine the approximate distance to your raid members.
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsSpellInRange)
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
---@param unit string UnitId The unit to use as a target for the spell.
---@return number? inRange 1 if the target is in range of the spell, 0 if the target is not in range of the spell, nil if the provided arguments were invalid or inapplicable.
function IsSpellInRange(index, bookType, unit) end

---Checks if a spell is in range.
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Spell.IsSpellInRange)
---@param spellID number
---@param unit string
---@return boolean
function C_Spell.IsSpellInRange(spellID, unit) end

---Checks if a spellbook item is in range.
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_SpellBook.IsSpellBookItemInRange)
---@param spellID number
---@param unit string
---@return boolean
function C_SpellBook.IsSpellBookItemInRange(spellID, unit) end

---Determines whether a spell can be used by the player character.<br>
---This function was deprecated in patch 11.0.0 and will be removed in patch 11.0.2.
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsUsableSpell)
---@deprecated
---@param spell number|string Spell ID or Name. When passing a name requires the spell to be in your Spellbook.
---@return boolean usable True if the spell is usable, false otherwise.
---@return boolean noMana True if the spell can not be cast due to low mana, false otherwise.
function IsUsableSpell(spell) end

---Determines whether a spell can be used by the player character.<br>
---This function was deprecated in patch 11.0.0 and will be removed in patch 11.0.2.
---[Documentation](https://warcraft.wiki.gg/wiki/API_IsUsableSpell)
---@deprecated
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
---@return boolean usable True if the spell is usable, false otherwise.
---@return boolean noMana True if the spell can not be cast due to low mana, false otherwise.
function IsUsableSpell(index, bookType) end

---Checks if a spellbook item is usable.
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_SpellBook.IsSpellBookItemUsable)
---@param spellID number
---@return boolean
function C_SpellBook.IsSpellBookItemUsable(spellID) end

---Checks if a spell is usable.
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_Spell.IsSpellUsable)
---@param spellID number
---@return boolean
function C_Spell.IsSpellUsable(spellID) end

---Places a spell onto the cursor.<br>
---This function will put a spell on mouse cursor.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_PickupSpell)
---@param spellID number spell ID of the spell to pick up.
function PickupSpell(spellID) end

---Picks up a skill from spellbook so that it can subsequently be placed on an action bar.<br>
---Restricted API.
---[Documentation](https://warcraft.wiki.gg/wiki/API_PickupSpellBookItem)
---@param spell number|string Spell ID or Name. When passing a name requires the spell to be in your Spellbook.
function PickupSpellBookItem(spell) end

---Picks up a skill from spellbook so that it can subsequently be placed on an action bar.<br>
---Restricted API.
---[Documentation](https://warcraft.wiki.gg/wiki/API_PickupSpellBookItem)
---@param index number Spellbook slot index, ranging from 1 through the total number of spells across all tabs and pages.
---@param bookType string BOOKTYPE_SPELL or BOOKTYPE_PET depending on if you wish to query the player or pet spellbook.
function PickupSpellBookItem(index, bookType) end

