---@meta
--* GENERATED BY gemini-2.0-flash

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_StorePublic.HasPurchaseableProducts)
---@return boolean hasPurchaseableProducts
function C_StorePublic.HasPurchaseableProducts() end

