---@meta
--* GENERATED BY gemini-2.0-flash

---Returns the texture of the active tracking buff.<br>
---This API only exists in Cata Classic and Classic Era. Removed in Patch 4.0.1.
---[Documentation](https://warcraft.wiki.gg/wiki/API_GetTrackingTexture)
---@return number? icon FileID - The texture of the active tracking buff, or nil if noone.
function GetTrackingTexture() end

