---@meta
--* GENERATED BY gemini-2.0-flash

---Needs summary.<br>
---[Documentation](https://warcraft.wiki.gg/wiki/API_C_UIWidgetManager.GetTextureWithStateVisualizationInfo)
---@param widgetID number
---@return TextureWithStateVisualizationInfo? widgetInfo
function C_UIWidgetManager.GetTextureWithStateVisualizationInfo(widgetID) end

